### ISSUE TITLE
ReactJS

### ISSUE THREAD

**Issue by bsideup** [cloudbees/pipeline-editor-plugin#7]
Hi guys,

Looks like this project is a really nice usecase for ReactJS ( http://facebook.github.io/react/ )

I highly recommend you to check. I can also guide a little bit

**Comment by michaelneale** [comment]
@bsideup yeah someone is looking exactly that that, I like it. Downside is... well the very short lifespan of most js frameworks in their current form (hopefully react ends up more like jquery, and less like... well all the others).
